theme = "duckquill"

title = "Dene Hoffman"
base_url = "https://denehoffman.com"
description = "My personal website and blog"

compile_sass = true
minify_html = true
generate_feeds = true
feed_filenames = ["rss.xml", "atom.xml"]
build_search_index = true
author = "Dene Hoffman"

default_language = "en"
taxonomies = [{ name = "tags", feed = true }]

[markdown]
smart_punctuation = true
bottom_footnotes = true
github_alerts = true

[markdown.highlighting]
light_theme = "solarized-light"
dark_theme = "solarized-dark"
extra_grammars = ["syntaxes/math.json"]

[search]
index_format = "fuse_json"

[extra]
accent_color = "#a04b24"
accent_color_dark = "#e59668"
issues_url = "https://github.com/denehoffman/denehoffman.github.io/issues"
source_url = "https://github.com/denehoffman/denehoffman.github.io"
show_copy_button = true
show_reading_time = true
show_share_button = true
show_backlinks = true
katex = true
card = true
styles = ["overrides.css"]
scripts = ["home-links.js", "mobile-nav.js", "bubble-chamber.js"]


csp = [
  { directive = "font-src", domains = [
    "'self'",
  ] },
  { directive = "img-src", domains = [
    "'self'",
    "https:",
    "data:",
  ] },
  { directive = "media-src", domains = [
    "'self'",
    "https:",
  ] },
  { directive = "script-src", domains = [
    "'self'",
  ] },
  { directive = "style-src", domains = [
    "'self'",
    "'unsafe-inline'",
  ] },
  { directive = "frame-src", domains = [
    "https://player.vimeo.com",
    "https://www.youtube-nocookie.com",
    "https://toot.community",
  ] },
  { directive = "connect-src", domains = [
    "https://toot.community",
  ] },
  { directive = "base-uri", domains = [
    "'none'",
  ] },
  { directive = "form-action", domains = [
    "'none'",
  ] },
]

[extra.nav]
show_feed = true
show_theme_switcher = true
show_repo = true
links = [
  { url = "@/blog/_index.md", name = "Blog" },
  { url = "@/publications/index.md", name = "Publications" },
  { url = "https://github.com/denehoffman/CV/blob/main/cv.pdf", name = "CV" },
  { name = "Projects", menu = [
    { url = "@/projects/laddu/index.md", name = "laddu" },
    { url = "@/projects/ganesh/index.md", name = "ganesh" },
    { url = "https://github.com/denehoffman/maryada", name = "maryada" },
    { url = "https://github.com/denehoffman/gluex-rs", name = "gluex-rs" },
  ] },
]

[extra.footer]
show_copyright = true
