theme = "duckquill"

title = "Dene Hoffman"
base_url = "https://denehoffman.com"
description = "My personal website and blog"

compile_sass = true
minify_html = true
generate_feeds = true
feed_filenames = ["rss.xml", "atom.xml"]
build_search_index = true
author = "Dene Hoffman"

default_language = "en"
taxonomies = [{ name = "tags", feed = true }]

[markdown]
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
  { theme = "solarized-dark", filename = "syntax-theme-dark.css" },
  { theme = "solarized-light", filename = "syntax-theme-light.css" },
]
smart_punctuation = true
bottom_footnotes = true

[search]
index_format = "fuse_json"

[extra]
accent_color = "#fe640b"
accent_color_dark = "#fab387"
issues_url = "https://github.com/denehoffman/denehoffman.github.io/issues"
source_url = "https://github.com/denehoffman/denehoffman.github.io"
show_copy_button = true
show_reading_time = true
show_share_button = true
show_backlinks = true
katex = true


csp = [
  { directive = "font-src", domains = [
    "'self'",
  ] },
  { directive = "img-src", domains = [
    "'self'",
    "https:",
    "data:",
  ] },
  { directive = "media-src", domains = [
    "'self'",
    "https:",
  ] },
  { directive = "script-src", domains = [
    "'self'",
  ] },
  { directive = "style-src", domains = [
    "'self'",
    "'unsafe-inline'",
  ] },
  { directive = "frame-src", domains = [
    "https://player.vimeo.com",
    "https://www.youtube-nocookie.com",
    "https://toot.community",
  ] },
  { directive = "connect-src", domains = [
    "https://toot.community",
  ] },
  { directive = "base-uri", domains = [
    "'none'",
  ] },
  { directive = "form-action", domains = [
    "'none'",
  ] },
]

[extra.nav]
show_feed = true
show_theme_switcher = true
show_repo = true
links = [
  { url = "@/blog/_index.md", name = "Blog" },
  { url = "@/publications/index.md", name = "Publications" },
  { url = "https://github.com/denehoffman/CV/blob/main/cv.pdf", name = "CV" },
  { name = "Projects", menu = [
    { url = "@/projects/laddu/index.md", name = "laddu" },
    { url = "@/projects/ganesh/index.md", name = "ganesh" },
    { url = "@/projects/modak/index.md", name = "modak" },
    { url = "@/projects/rustitude/index.md", name = "rustitude" },
  ] },
]

[extra.footer]
show_copyright = true
